### ISSUE TITLE
Bootstrap a React Native project

### ISSUE THREAD

**Issue by lindlof** [simplekitchen/simplekitchen-app#1]
Bootstrap the project so that we can start developing app. You can use a tool such as `react-native init` command from https://www.npmjs.com/package/react-native-cli

Technical requirements:
- App can be compiled to Android and iOS systems
- Instructions and simple commands for running a development version of the app in Android and iOS are provided
- Instructions and simple commands for creating Android and iOS production deployments are provided
- Instructions are in the repository's `README.md` file and the README file is simple and straightforward

**Comment by bezawork** [comment]
please provide detailed description

**Comment by lindlof** [comment]
@bezawork description updated
